# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  notionfinance:
    image: notionfinance
    build:
      context: .
      dockerfile: NotionFinance/Dockerfile
    ports:
      - 7047:7047
    environment:
      - ASPNETCORE_URLS=http://+:7047
